[13] - Añadir función getCompaniesList para obtener listado
oconi540/charger_fastify_cli pull request #14
Opened 2024-04-30 09:14 UTC by oconi540

**Descripción**

Añadir función getCompaniesList para obtener el listado de empresas.

Resolve #13 

**Verificación**

http://127.0.0.1:3000/companies
{
    "data": [
        {
            "company_id": 1,
            "name": "Tesla Inc.",
            "founded_year": 2003,
            "revenue": "4680.00",
            "employees_count": 70000
        },
        {
            "company_id": 2,
            "name": "Apple Inc.",
            "founded_year": 1976,
            "revenue": "365.00",
            "employees_count": 154000
        },
        {
            "company_id": 3,
            "name": "Google LLC",
            "founded_year": 1998,
            "revenue": "2000.00",
            "employees_count": 150000
        }
    ]
}

2024-04-30 10:05 UTC, LeWricka approved these changes
Un detalle y ok to merge

2024-04-30 10:05 UTC, LeWricka commented on db/migrations/20240430063504_companies_list_table.ts
> +    return knex.schema.createTable('companies_list', function (table) {
En general cuidado con el concepto List. Un List suele estar asociado a tener ciertas propiedades como ordenar, paginar, etc... que en este caso no aplican.
Más en concreto de cara a modelar una bd, no tienes una lista, tienes compañías, lo mismo que en cargadores no tienes una charger_list, tienes una tabla charge que luego tendrá x registros.
Yo cambiaría esto a company

2024-04-30 10:05 UTC, LeWricka commented on src/getCompaniesList.ts
> +async function getCompaniesList(request: Request, reply: Reply): Promise<void> {
aquí lo mismo que he comentado con las listas, cuidado que puede tener más acepciones que un simple conjunto de elementos -> getCompanies?

2024-04-30 10:43 UTC, estherelizagaray requested changes
3 chorradicas :)

2024-04-30 10:43 UTC, estherelizagaray commented on db/migrations/20240430063504_companies_list_table.ts
> +        table.increments('company_id').primary();
Le pondría como nombre simplemente id, ya estás en la tabla de companies

2024-04-30 10:43 UTC, estherelizagaray commented on src/app.ts
> +import getCompaniesList from "./getCompaniesList";
Comillas simples :)

2024-04-30 10:43 UTC, estherelizagaray commented on src/getCompaniesList.ts
> +export default getCompaniesList;
Esta línea la podemos quitar y dejar en la línea 7:
`export const getCompaniesList = async function.....`

2024-05-02 07:21 UTC, estherelizagaray approved these changes
Ok to merge, pero actualiza el título de la PR. No hablaría de "función", solemos hablar más de lo que hace la funcionalidad

2024-05-02 07:44 UTC, merged