[15] - Endpoint que devuelva un listado de empresas en base al parámetro que nos pasen
oconi540/charger_fastify_cli pull request #16
Opened 2024-04-30 15:00 UTC by oconi540

**Descripción**

Modificar función getCompanies teniendo en cuenta las siguientes reglas:

* Si no hay ninguna compañía en vez de devolver el listado de usuarios, devolveremos un mensaje 200 {"estado" : "No hay compañías" }
* Si no se pasa ningún parámetro a la petición, devolveremos el listado sin ningún tipo de orden
* Si por parámetro nos pasan el campo order_by filtraremos la respuesta en base al parámetro que nos pasen:
    * /companies?order_by=employees -> devolveremos el listado ordenador de mayor a menor por número de empleados
    * /companies?order_by=year -> devolveremos el listado ordenador de más antigua a nueva en base a año de creación de empresa
* Si nos pasan el parámetro order_by vacío, devolveremos un error 400 -> { "error": "order_by no puede ser vacío"}
* Si nos pasan el parámetro order_by con otro valor que no sea employees o year, devolveremos un error 400 -> { "error": "order_by no válido"}

Resolve #15

**Verificación**

http://127.0.0.1:3000/companies

{
    "data": [
        {
            "company_id": 1,
            "name": "Tesla Inc.",
            "founded_year": 2003,
            "revenue": "4680.00",
            "employees_count": 70000
        },
        {
            "company_id": 2,
            "name": "Apple Inc.",
            "founded_year": 1976,
            "revenue": "365.00",
            "employees_count": 154000
        },
        {
            "company_id": 3,
            "name": "Google LLC",
            "founded_year": 1998,
            "revenue": "2000.00",
            "employees_count": 150000
        }
    ]
}

http://127.0.0.1:3000/companies?order_by=employees

http://127.0.0.1:3000/companies?order_by=year

{
    "data": [
        {
            "company_id": 2,
            "name": "Apple Inc.",
            "founded_year": 1976,
            "revenue": "365.00",
            "employees_count": 154000
        },
        {
            "company_id": 3,
            "name": "Google LLC",
            "founded_year": 1998,
            "revenue": "2000.00",
            "employees_count": 150000
        },
        {
            "company_id": 1,
            "name": "Tesla Inc.",
            "founded_year": 2003,
            "revenue": "4680.00",
            "employees_count": 70000
        }
    ]
}

http://127.0.0.1:3000/companies?order_by=

{
    "error": "order_by no puede ser vacío"
}

http://127.0.0.1:3000/companies?order_by=540

{
    "error": "order_by no válido"
}

2024-05-02 09:35 UTC, estherelizagaray requested changes

2024-05-02 09:35 UTC, estherelizagaray commented on src/getCompanies.ts
> +        reply.send({ data: companies });
Cuantos menos ifs encadenemos, mejor se entiende el código. Intenta ir devolviendo cosas en cuanto sepas que hay que salir. Este concepto se llama cláusula de guarda: https://secture.com/blog/que-son-las-clausulas-de-guarda-con-ejemplos/

2024-05-02 09:35 UTC, estherelizagaray commented on src/getCompanies.ts
> +            return;
No sé si necesitas estos return;

2024-05-02 11:58 UTC, estherelizagaray requested changes

2024-05-02 11:58 UTC, estherelizagaray commented on src/getCompanies.ts
> +            companies = await knexInstance('company').select('*').orderBy('founded_year', 'asc');
Igual como pequeño refactor, podríamos sacar todo este código a una función que sea getCompaniesSortedBy(sortBy)? Puedes mirar el concepto Repositorio en este artículo, sin volverte muy loco de momento https://our-academy.org/posts/el-patron-repository:-implementacion-y-buenas-practicas

2024-05-06 15:12 UTC, estherelizagaray requested changes

2024-05-06 15:12 UTC, estherelizagaray commented on src/getCompanies.ts
> +        const companyRepository: CompanyRepository = new KnexCompanyRepository();
Creo que no hace falta tipar una variable que justo estás inicializando, creo que lo puede inferir solo. Si pasas el cursor por encima de la variable con la tecla comand pulsada te dice de qué tipo es. Si no mañana en persona te enseño ;)

```suggestion
        const companyRepository = new KnexCompanyRepository();
```

2024-05-06 15:12 UTC, estherelizagaray commented on src/companyRepository.ts
> +        throw new Error('sortBy no válido');
Estos 2 errores que estás echando desde este repositorio, luego desaparecerán en el catch de getCompanies, no? Mañana lo vemos si no

2024-05-06 15:12 UTC, estherelizagaray commented on src/companyRepository.ts
> +        }
Creo que saber el orden de ordenación (asc/desc) no es responsabilidad del repositorio. Ya comentaremos en persona, más que nada por que te suene de algo el tema de responsabilidades.

2024-05-07 09:34 UTC, oconi540 commented on src/companyRepository.ts
> +        }
Estoy teniendo dificultades con el tema de ordenación asc/desc.

2024-05-07 15:15 UTC, estherelizagaray requested changes

2024-05-07 15:15 UTC, estherelizagaray commented on src/getCompanies.ts
> +        const companies = await companyRepository.getCompaniesSortedBy(order_by, sortDirection);
Una variable está en camelCase y la otra en snake_case. Solemos usar más camelCase, pero sería convenio de equipo. Elige una y palante :)

2024-05-07 15:15 UTC, estherelizagaray commented on src/getCompanies.ts
> +        }
Creo que nunca va a llegar a este if. Porque en la línea 24 estás saliendo siempre con lo que te ha devuelto el repo.

2024-05-08 08:48 UTC, estherelizagaray approved these changes

2024-05-08 09:06 UTC, merged