[18] - Generar token de autenticación con respuesta de error
oconi540/charger_fastify_cli pull request #19
Opened 2024-05-07 14:11 UTC by oconi540

**Descripción**
Este endpoint permite generar un token de autenticación mediante la provisión de un id y un secret. Hemos tenido solo en cuenta los mensajes de error.

Resolve #18 

**Verificación**
POST http://localhost:3000/oauth/token

En la pestaña "Body" en Postman, seleccionamos "raw" y "JSON"

{
   
}

Body:
{
    "error": "Verifica el id y el secret son obligatorios."
}

POST http://localhost:3000/oauth/token

En la pestaña "Body" en Postman, seleccionamos "raw" y "JSON"

{
    "id": 1,
    "secret": "secret"
}

Body:
{
    "error": "Credenciales inválidas. Verifica el id y el secret proporcionados."
}

2024-05-07 14:57 UTC, LeWricka approved these changes
Dos cosillas y ok to merge

2024-05-07 14:57 UTC, LeWricka commented on src/app.ts
>  async function app(fastify: FastifyInstance, opts: any){
Ahora que tenemos varias rutas, échales un ojo en general, a ver si algo te llama la atención o a ver si algo se puede mejorar

2024-05-07 14:57 UTC, LeWricka commented on src/generateToken.ts
> +
Este espacio no es necesario, elimínalo

2024-05-07 14:57 UTC, LeWricka commented on src/generateToken.ts
> +        console.error('Error', error);
Qué error puede ocurrir que no lleve hasta aquí? igual no hay ningún caso y podemos eliminarlo?

2024-05-07 15:03 UTC, oconi540 commented on src/app.ts
>  async function app(fastify: FastifyInstance, opts: any){
Quedaría más curioso si realizo los export e import de la misma manera no? Utilizando los { }

2024-05-07 15:35 UTC, estherelizagaray requested changes

2024-05-07 15:35 UTC, estherelizagaray commented on src/generateToken.ts
> +export const generateToken = async function generateToken(request: Request, reply: Reply): Promise<void> {
No necesitas tener 2 veces el nombre de la función. Incluso puedes refactorizarlo haciendo un arrow function: https://bootcamp.uxdesign.cc/arrow-functions-vs-regular-functions-in-javascript-29db7928d696

2024-05-07 15:35 UTC, estherelizagaray commented on src/generateToken.ts
> +        const { id, secret } = request.body as { id: number; secret: string };
Creo que este `id: number` no es verdad. Si le quitas el tipado y haces lo del comand y pasar por encima verás el tipo que tiene, que será string, porque todo lo que te entra por la petición son strings. Si luego queremos trabajar con number, lo tenemos que pasar a int.

2024-05-07 15:35 UTC, estherelizagaray commented on src/generateToken.ts
> +}
Solemos poner lo primero la función principal, generateToken. Y debajo las que son "menos importantes", porque se usan dentro de generateToken.

2024-05-07 15:35 UTC, estherelizagaray commented on src/generateToken.ts
> +    const company = await knexInstance('company').where({ id, secret }).first();
Para acceder a la tabla de compañías ahora tienes un repositorio que puedes usar :)

2024-05-08 08:57 UTC, estherelizagaray requested changes

2024-05-08 08:57 UTC, estherelizagaray commented on src/companyRepository.ts
> +    async findByCredentials(id: number, secret: string) {
Falta tipar lo que devuelve, no?

2024-05-08 08:57 UTC, estherelizagaray commented on src/generateToken.ts
> +        const isValid = await verifyCredentials(numericId, secret);
Cuando hablamos de credentials suele ser user y password. En este caso es más el token, no?
Y otra cosa, igual no necesitamos numericId como variable aparte, se puede meter directamente aquí el parseInt(id) y se entiende bien.

2024-05-08 09:48 UTC, oconi540 commented on src/generateToken.ts
> +        const isValid = await verifyCredentials(numericId, secret);
Entiendo que en este caso es el token, si.

2024-05-08 09:55 UTC, oconi540 commented on src/companyRepository.ts
> +    async findByCredentials(id: number, secret: string) {
Si, tienes razón.

2024-05-08 15:17 UTC, estherelizagaray approved these changes

2024-05-09 06:35 UTC, merged