[20] - Generar token de autenticación con respuesta de éxito
oconi540/charger_fastify_cli pull request #21
Opened 2024-05-09 06:33 UTC by oconi540

**Descripción**
Este endpoint permite generar un token de autenticación mediante la provisión de un id y un secret. Hemos tenido en cuenta la respuesta exitosa.

Resolve #20 

**Verificación**
POST http://localhost:3000/oauth/token

En la pestaña "Body" en Postman, seleccionamos "raw" y "JSON"
```
{
    "id": 3,
    "secret": "secret_3"
}
```
Body:
```
{
    "access_token": "17151779180199481",
    "expires_in": 143253,
    "refresh_token": "17151779180193799"
}
```

2024-05-13 10:47 UTC, estherelizagaray requested changes

2024-05-13 10:47 UTC, estherelizagaray commented on db/seeds/token.ts
Si como hemos quedado, no necesitas tener datos este archivo te lo puedes quitar totalmente :)

2024-05-13 10:47 UTC, estherelizagaray commented on src/generateToken.ts
Este archivo también sobra? Ahora lo has pasado todo a insertToken, no?

2024-05-13 10:47 UTC, estherelizagaray commented on src/insertToken.ts
> +        const expiresIn = new Date(currentDate.getTime() + (7 * 24 * 60 * 60 * 1000));
Mira esto a ver si puedes simplificar este cálculo https://www.geeksforgeeks.org/how-to-add-days-to-date-in-javascript/

2024-05-14 07:58 UTC, estherelizagaray requested changes

2024-05-14 07:58 UTC, estherelizagaray commented on src/models.ts
> +export interface Token {
Solemos poner los modelos y los repos en archivos separados. Y los organizamos por carpetas mejor :)

2024-05-14 07:58 UTC, estherelizagaray commented on src/repository.ts
> +    async findCompanyByIdAndSecret(id: number, secret: string): Promise<Company | null> {
Buen naming!

2024-05-14 07:58 UTC, estherelizagaray commented on src/repository.ts
> +    async insertToken(token: Token): Promise<void> {
Este método no está definido en su interfaz

2024-05-14 07:58 UTC, estherelizagaray commented on src/insertTokenHandler.ts
> +        expiresIn.setDate(currentDate.getDate() + 7);
Creo que esto sería lo mismo?
```suggestion
        const expiresIn = new Date();
        expiresIn.setDate(expiresIn.getDate() + 7);
```

2024-05-14 07:58 UTC, estherelizagaray commented on src/app.ts
> +  fastify.post('/oauth/token', insertTokenHandler);
Lo de ponerle Handler sería algo que se lo pondríamos o a todas o a ninguna.

2024-05-14 08:20 UTC, oconi540 commented on src/repository.ts
> +    async insertToken(token: Token): Promise<void> {
Con este comentario te refieres a que debería de añadir insertToken en el interface Repository no?

2024-05-14 08:22 UTC, estherelizagaray commented on src/repository.ts
> +    async insertToken(token: Token): Promise<void> {
Eso es. Los métodos que tienes en el KnexRepository tienen que estar definidos también en la interfaz Repository. Pero por otra parte, como lo vas a separar en 2 repositorios, al final estará en otra interfaz, pero la idea es esa.

2024-05-14 09:56 UTC, estherelizagaray approved these changes

2024-05-14 10:01 UTC, merged