[5] - Devolver la duración de cargas en base a fecha de inicio y fecha de fin
oconi540/charger_fastify_cli pull request #7
Opened 2024-04-25 08:16 UTC by oconi540

**Descripción**

Se modifica función getHistoryCharger, con esta modificación la propiedad 'duration' de cada objeto de cargador se calculará dinámicamente en base a la diferencia entre 'start_date' y 'end_date'. Esto garantiza que obtengas la duración precisa en minutos.

Resolve #5 

**Verificación**

Entre 'start_date': '2024-03-31T22:00:00.000Z' y 'end_date': '2024-04-29T22:00:00.000Z' hay 41760 minutos de diferencia.
Entre 'start_date': '2024-03-14T23:00:00.000Z' y 'end_date': '2024-04-29T22:00:00.000Z' hay 66180 minutos de diferencia.
Entre 'start_date': '2024-04-09T22:00:00.000Z' y 'end_date': '2024-04-24T22:00:00.000Z' hay 1440 minutos de diferencia.

2024-04-25 08:22 UTC, estherelizagaray requested changes

2024-04-25 08:22 UTC, estherelizagaray commented on src/app.ts
> +  fastify.get('/charges/:id', getHistoryCharger);
No usas el id para nada, no?

2024-04-25 08:22 UTC, estherelizagaray commented on src/getHistoryCharger.ts
>  async function getHistoryCharger(request: Request, reply: Reply): Promise<void> {
Yo lo llamaría getCharges o getChargesHistory

2024-04-25 08:22 UTC, estherelizagaray commented on src/getHistoryCharger.ts
> +        const chargers = await knexInstance('charges_history');
Esto no son cargadores, son cargas. Por lo tanto le llamaría charges

2024-04-25 08:24 UTC, oconi540 commented on src/app.ts
> +  fastify.get('/charges/:id', getHistoryCharger);
Por ahora no, hable con Iker en dejarlo así pero esta pendiente de modificar la lógica de la función.

2024-04-25 09:45 UTC, estherelizagaray approved these changes

2024-04-25 18:33 UTC, LeWricka reviewed
MIra este comentario antes de cerrar pls

2024-04-25 18:33 UTC, LeWricka commented on src/getChargesHistory.ts
> +                const startDate = new Date(charges.start_date);
pregunta, entiendo que aquí no estamos devolviendo resto de campos que tenemos en bd y no tenemos que calcular, ¿no? ¿por qué? creo que no había ninguna otra issue para eso, de hecho diría que era la anterior, o me estoy perdiendo algo, que es muy posible...jaja

2024-04-26 06:42 UTC, oconi540 commented on src/getChargesHistory.ts
> +                const startDate = new Date(charges.start_date);
En esta issue devolvemos todos los campos que tenemos en db, pero teniendo en cuenta la fecha de inicio y la fecha de fin para devolver la duración que corresponde y no un número en concreto. Me explicó? jaj

2024-04-29 07:57 UTC, LeWricka commented on src/getChargesHistory.ts
> +                const startDate = new Date(charges.start_date);
ok!

2024-04-29 07:58 UTC, LeWricka approved these changes
Ok to merge

2024-04-29 08:13 UTC, estherelizagaray requested changes

2024-04-29 08:13 UTC, estherelizagaray commented on db/migrations/20240424152127_charges_history_table.ts
> +    return knex.schema.createTable('charges_history', function (table) {
Las migraciones no se pueden modificar. En un proyecto real ya se habrían ejecutado en prod o en otras máquinas del equipo. Si necesitas renombrar una tabla, hay que hacer otra migración para eso.

2024-04-29 08:13 UTC, estherelizagaray commented on src/app.ts
> +  fastify.get('/charges/:id', getChargesHistory);
Este :id si de momento no lo usamos lo suyo sería quitarlo. Y en el momento en que getChargesHistory devuelva las cargas por id, se metería.

2024-04-29 09:59 UTC, merged